CMAKE_MINIMUM_REQUIRED(VERSION 3.12)
PROJECT(kfext_mock_native)

SET(CMAKE_CXX_STANDARD 17)

if(KF_SOURCE_HOME)
    MESSAGE("KF_SOURCE_HOME set to ${KF_SOURCE_HOME}")
else(KF_SOURCE_HOME)
    SET(KFC_DEV_DIR "../..")
    GET_FILENAME_COMPONENT(KF_SOURCE_HOME ${KFC_DEV_DIR} ABSOLUTE)
    MESSAGE("KF_SOURCE_HOME set to ${KF_SOURCE_HOME}")
endif (KF_SOURCE_HOME)

INCLUDE_DIRECTORIES("${KF_SOURCE_HOME}/build/dist/include")
INCLUDE_DIRECTORIES("${KF_SOURCE_HOME}/cpp/yijinjing/include")
INCLUDE_DIRECTORIES("${KF_SOURCE_HOME}/cpp/wingchun/include")
INCLUDE_DIRECTORIES("${KF_SOURCE_HOME}/build/deps/nanomsg-1.1.5/include")
INCLUDE_DIRECTORIES("${KF_SOURCE_HOME}/deps/spdlog-1.3.1/include")
INCLUDE_DIRECTORIES("${KF_SOURCE_HOME}/deps/fmt-5.3.0/include")
INCLUDE_DIRECTORIES("${KF_SOURCE_HOME}/deps/rxcpp-4.1.0/include")
INCLUDE_DIRECTORIES("${KF_SOURCE_HOME}/deps/json-3.5.0/single_include")
LINK_DIRECTORIES("${KF_SOURCE_HOME}/build")

ADD_SUBDIRECTORY(../../deps/pybind11-2.10.4 "${PROJECT_BINARY_DIR}/pybind11")

AUX_SOURCE_DIRECTORY(src SOURCE_FILES)
PYBIND11_ADD_MODULE(${PROJECT_NAME} SHARED ${SOURCE_FILES})
SET_TARGET_PROPERTIES(${PROJECT_NAME} PROPERTIES LIBRARY_OUTPUT_DIRECTORY "${KF_SOURCE_HOME}/python/extensions/mock")
TARGET_LINK_LIBRARIES(${PROJECT_NAME} PRIVATE wingchun yijinjing)
